#!/usr/bin/env bash

set -euo pipefail

name=$(basename "$0")
host_path="/usr/local/bin:/usr/bin:/bin"

unset APPDIR
unset GOWIN_ICUDTL_PATH
unset LD_LIBRARY_PATH
unset LD_PRELOAD
unset QML2_IMPORT_PATH
unset QT_PLUGIN_PATH
unset QT_QPA_PLATFORM_PLUGIN_PATH
unset QTWEBENGINEPROCESS_PATH
unset QTWEBENGINE_CHROMIUM_FLAGS
unset QTWEBENGINE_LOCALES_PATH
unset QTWEBENGINE_RESOURCES_PATH

export PATH="$host_path"

run_host() {
  local command_name="$1"
  shift

  local command_path
  command_path=$(PATH="$host_path" command -v "$command_name" || true)
  if [ -n "$command_path" ]; then
    exec "$command_path" "$@"
  fi
}

open_file_manager() {
  if PATH="$host_path" command -v dolphin >/dev/null 2>&1; then
    run_host dolphin "$@"
  fi
  if PATH="$host_path" command -v xdg-open >/dev/null 2>&1; then
    run_host xdg-open "$@"
  fi
}

open_terminal() {
  local workdir="${PWD:-$HOME}"
  local arg

  while [ "$#" -gt 0 ]; do
    arg="$1"
    shift
    case "$arg" in
      --working-directory=*)
        workdir="${arg#--working-directory=}"
        ;;
      --default-working-directory=*)
        workdir="${arg#--default-working-directory=}"
        ;;
      --workdir=*)
        workdir="${arg#--workdir=}"
        ;;
      --working-directory|--default-working-directory|--workdir)
        if [ "$#" -gt 0 ]; then
          workdir="$1"
          shift
        fi
        ;;
      *)
        if [ -d "$arg" ]; then
          workdir="$arg"
        fi
        ;;
    esac
  done

  if PATH="$host_path" command -v konsole >/dev/null 2>&1; then
    run_host konsole --workdir "$workdir"
  fi

  if PATH="$host_path" command -v xterm >/dev/null 2>&1; then
    cd "$workdir"
    run_host xterm
  fi
}

case "$name" in
  code|vscodium)
    run_host codium "$@"
    ;;
  nautilus|thunar)
    open_file_manager "$@"
    ;;
  open-file-location)
    open_file_manager "$@"
    ;;
  gnome-terminal|kgx|xfce4-terminal|mate-terminal|lxterminal|terminator)
    open_terminal "$@"
    ;;
esac

run_host "$name" "$@"

printf '%s: host command not found: %s\n' "$0" "$name" >&2
exit 127
